add notification after mail was sended
SoftwareBrothers/mailinger pull request #46
Opened 2019-03-18 22:20 UTC by mfka

2019-03-18 22:23 UTC, plorencrstit commented on src/components/Sender/Sender.tsx
> +        props.enqueueSnackbar(`Email to: ${recipient.email} was sended!`, {
`was sent`

2019-03-19 07:38 UTC, mfka commented
@bartekczyz dzisiaj spróbuję dopisać testy :)

2019-03-19 08:16 UTC, bartekczyz requested changes
Couple of changes are required

2019-03-19 08:16 UTC, bartekczyz commented on src/components/Sender/Sender.tsx
> +import PropTypes from 'prop-types';
🐛 Don't use 'prop-types' with TypeScript

2019-03-19 08:16 UTC, bartekczyz commented on src/components/Sender/Sender.tsx
> +const Sender = (props: any) => {
🐛 Props are not `any`. Define props as follows:

```ts
import { withSnackbar, withSnackbarProps } from 'notistack';

// ...

type Props = withSnackbarProps;

const Sender = (props: Props) => {
// ...
```

2019-03-19 08:16 UTC, bartekczyz commented on src/components/Sender/Sender.tsx
> +export default withSnackbar(Sender);
🐛 This should be memoized

```suggestion
export default memo(withSnackbar(Sender));
```

2019-03-19 08:16 UTC, bartekczyz commented on src/App.tsx
> +            {user ? <Steps /> : null}
🤷‍♂️ By the way you can simplify this

```suggestion
            {user && <Steps />}
```

2019-03-19 08:16 UTC, bartekczyz commented on src/components/Sender/Sender.tsx
> +Sender.propTypes = {
🐛 Remove all `propTypes` references

2020-09-29 19:37 UTC, bartekczyz approved these changes
Let's merge it @mfka

2021-12-17 19:54 UTC, closed without merging